scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: myapp
    scrape_interval: 10s
    static_configs:
      - targets:
          - myapp:2112
  - job_name: myappdb
    scrape_interval: 10s
    static_configs:
      - targets:
          - myappdb:3329

